- .github/workflows/publish.yml
- CHANGELOG.md
This adds a manually-triggered GitHub Actions workflow which will automatically:
* Choose a new version number
* Update CHANGELOG.md
* Update cargo.toml for both crates
* Commit the above changes and tag the release
* Add a GitHub release with the changelog summary (currently tagged as "prerelease")
* Publish the c2pa crate to crates.io (I'll add c2patool in a subsequent PR)
NOTE: This workflow can only be triggered by GitHub users with commit access to this repo.
> Add workflow for automatically releasing c2pa crate

- .github/workflows/ci.yml
- c2patool/Cargo.toml
Intra-repo dependencies are not allowed when publishing on crates.io.
> Fix dependency reference from c2patool crate to c2pa crate

- sdk/examples/custom_assertion.rs
- sdk/src/assertion.rs
- sdk/src/assertions/actions.rs
- sdk/src/assertions/creative_work.rs
- sdk/src/assertions/data_hash.rs
- sdk/src/assertions/ingredient.rs
- sdk/src/assertions/metadata.rs
- sdk/src/assertions/schema_org.rs
- sdk/src/assertions/thumbnail.rs
- sdk/src/assertions/user.rs
- sdk/src/assertions/user_cbor.rs
- sdk/src/assertions/uuid_assertion.rs
- sdk/src/lib.rs
Make Assertions opaque in the public SDK
AssertionDecodeResult is no longer exposed
> Make Assertions opaque in the public SDK

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
This update changes the README and pull request format to our "Sentence case" convention. I didn't include the Code of Conduct or Contributing documents since that seemed like standard Adobe documents - let me know if those should be added.
This might be contentious but I also removed the periods on the "Key features" bullet points since they were sentence fragments and not complete sentences.
> Update README and pull request template with formatting changes

- sdk/src/manifest_store.rs
`from_bytes`/`from_bytes_async` previously returned an `Option`, swallowing the error. This changes this over to use a `Result` instead of an `Option` as discussed with @gpeacock.
> (MINOR) Update from_bytes(_async) to return a Result

- sdk/examples/client/client.rs
- sdk/src/ingredient.rs
- sdk/src/manifest.rs
- sdk/tests/integration.rs
1141851: Add asset attribute getters for manifest
format, title, instance_id and thumbnail
make asset getter crate private
> (MINOR) Add asset attribute getters for manifest

- README.md
- sdk/Cargo.toml
- sdk/src/lib.rs
- sdk/src/store.rs
Adds xmp_write feature to make xmp-toolkit inclusion optional.
The dc:provenance XMP data will not be written unless this feature is enabled.
> Adds xmp_write feature to make xmp-toolkit inclusion optional

- sdk/src/manifest_assertion.rs
The 1.0 spec says:
>If a manifest contains three assertions of this type, the labels will be `stds.schema-org.CreativeWork`, `stds.schema-org.CreativeWork__1` and `stds.schema-org.CreativeWork__2`.
Currently, in the code, processing the labels above would give the following values for `instance`:
- `stds.schema-org.CreativeWork` would give `None`
- `stds.schema-org.CreativeWork__1` would give `None`
- `stds.schema-org.CreativeWork__2` would give `Some(2)`
This results in only `stds.schema-org.CreativeWork__2` giving back a value for `instance` in the serialized data. However, we should be getting:
- `stds.schema-org.CreativeWork` would give `None`
- `stds.schema-org.CreativeWork__1` would give `Some(1)`
- `stds.schema-org.CreativeWork__2` would give `Some(2)`
This adds a fix for this …
> Return assertion instance values starting at `1` instead of `2`

- make_test_images/Cargo.toml
- sdk/src/manifest.rs
- sdk/src/store.rs
Return specific errors for FileNotFound and Unsupported type
Remove Sec-CH-UA hint injection
> (MINOR) Return specific errors for FileNotFound and UnsupportedType

- sdk/src/assertions/bmff_hash.rs
- sdk/src/assertions/data_hash.rs
- sdk/src/asset_handlers/bmff_io.rs
- sdk/src/asset_handlers/png_io.rs
- sdk/src/claim.rs
- sdk/src/store.rs
- sdk/src/utils/cbor_types.rs
- sdk/src/utils/hash_utils.rs
The PR refactors the hashing of data to be more flexible:
-  removes memory copies during hashing
-  caps the maximum memory usage during hash generation/validation
- updates functions to allow content from various sources (in-memory, from asset, from stream, etc.)
- setup for hardware based hash generation  
- significant speedup for large files
> Refactor code to limit memory usage and remove data copies during hash generation

- .github/workflows/ci.yml
- sdk/Cargo.toml
Release 0.7.1 [failed to build on docs.rs](https://docs.rs/crate/c2pa/0.7.1) because the so-called "no-op" C++ code in XMP Toolkit contained a reference to a field that was disabled elsewhere. (See https://github.com/adobe/xmp-toolkit-rs/pull/67.)
This PR incorporates the fixed version of XMP Toolkit and and updates the PR validation loop to more closely mimic the docs.rs runtime environment so we detect future errors of this type.
> Fix broken documentation build

- deny.toml
This will be needed for the next XMP Toolkit release.
> Add Unicode license to allow-list

- CONTRIBUTING.md
Adds info on PR title prefixes `(IGNORE)`, `(MINOR)`, and `(MAJOR)`.  This came up in discussion earlier this week.
> (IGNORE) Add info on PR title prefixes (IGNORE), (MINOR), and (MAJOR) to contribution guidelines.

- sdk/src/jumbf_io.rs
Adding `application/x-c2pa-manifest-store` to the list of mime-types for manifest store files to comply with [the 1.0 spec](https://c2pa.org/specifications/specifications/1.0/specs/C2PA_Specification.html#_external_manifests).
> Update C2PA manifest store mime type

- sdk/src/status_tracker.rs
- sdk/src/store.rs
- sdk/src/validation_status.rs
Allows us to return complex errors while still adding them to logs. You can't copy an error, but you can display it.
> Convert status_log error val to a string so that we can return full errors

- .github/workflows/ci.yml
- .github/workflows/publish.yml
This adds steps to the CI and publish workflows to ensure that the correct semantic version bumps occur when breaking API changes are proposed.
This will cause a PR to fail validation if the `(MINOR)` tag is omitted when it should be present.
Similarly, we re-check during the release process and stop the release if a minor version change should have been triggered.
All of these will need to change to `(MAJOR)` once we do 1.0 release.
> (IGNORE) Enforce semantic versioning requirements during PR validation and publish workflows

- sdk/Cargo.toml
- sdk/src/ingredient.rs
- sdk/src/store.rs
Inrgredient::from_file was not returning manifest_data for remote manifests.
> manifest_data was missing for remote manifests

- .github/workflows/ci.yml
Grep exits non-zero when no results are found, but we don't want to fail the entire CI workflow because of that.
> (IGNORE) Disregard grep non-zero exit status

- sdk/src/cose_validator.rs
- sdk/src/store.rs
Add change to cose_validator so that certs without organization is not an error
Old CAI manifests may still have XMP jumbf references.  This PR check to make sure those references are valid URLs before attempting a remote manifest fetch.  Also fix bogus error when a certificate does not have an organization set.  That is not a C2PA requirement.
> Fix for XMP links being mistaken for remote URLs

- sdk/src/manifest.rs
Allow overriding a manifest thumbnail when the thumbnail feature is enabled.
> Fix manifest.set_thumbnail when add_thumbnails is enabled

- make_test_images/src/make_test_images.rs
- sdk/src/assertions/actions.rs
- sdk/src/manifest.rs
fix support for ingredientId on action and generate parameters.ingredient field when possible
Update make_test_images to add instanceId to actions
> Fixes support for instanceId on action and generate parameters.ingredient field when possible

- sdk/src/store.rs
- sdk/tests/fixtures/unsupported_type.txt
This PR allows us to make and validate unknown/unsupported asset types.  When an asset extension is unknown we will make an external manifest.
> Create external manifests for unknown types

- sdk/src/asset_handlers/jpeg_io.rs
Fix bug caused by using a non C2PA App11 segment.  Fix for issue: https://github.com/contentauth/c2pa-rs/issues/167
> Fix for using non-c2pa segment when add required segments

- .github/workflows/ci.yml
- README.md
- make_test_images/Cargo.toml
- sdk/Cargo.toml
Reason: Upstream dependency [openssl-src](https://crates.io/crates/openssl-src/versions) released a minor version upgrade (111.25.1+1.1.1t) a few days ago which _says_ that it bumps MSRV to 1.57.0, but that appears to be incorrect. Local testing shows that it no longer compiles with any version prior to 1.63.0.
> (MINOR) Bump MSRV to 1.63.0

- sdk/src/utils/hash_utils.rs
Working bmff_offset should not be written into the exclusion map
> Fix issue where value was inadvertently included in Exclusion structure

- sdk/src/store.rs
Update the asyn ingredient check to test for ingredient box hashes
> Fix async path to support ingredient box hashing

- rustfmt.toml
- sdk/src/assertions/bmff_hash.rs
- sdk/src/assertions/schema_org.rs
- sdk/src/asset_handlers/bmff_io.rs
- sdk/src/asset_handlers/png_io.rs
- sdk/src/asset_handlers/riff_io.rs
- sdk/src/asset_handlers/tiff_io.rs
- sdk/src/claim.rs
- sdk/src/hashed_uri.rs
- sdk/src/ingredient.rs
- sdk/src/manifest.rs
- sdk/src/manifest_store_report.rs
- sdk/src/store.rs
Among other things, enforces a blank line between method definitions. 
https://rust-lang.github.io/rustfmt/?version=v1.5.1&search=#reorder_impl_items
> (IGNORE) Enable `reorder_impl_items` rustfmt option

- README.md
Change relative link to absolute to fix doc build per @dkozma:
> ...the easy/quick fix is just to update the link to the CHANGELOG in the c2patool/c2pa-rs READMEs to be an absolute URL
> (IGNORE) Change relative link to absolute to fix doc build

- .github/workflows/ci.yml
- .github/workflows/publish.yml
actions-rs/toolchain appears to be unmaintained (Last commit was in 2020.)
> (IGNORE) Replace actions-rs/toolchain with dtolnay/rust-toolchain

- .github/workflows/ci.yml
- make_test_images/Cargo.toml
- sdk/Cargo.toml
I recently added these to XMP Toolkit's automation and they seem like good ideas. Adding them here:
* Run unit tests with default features disabled
* Run unit tests with minimum versions of direct dependencies
* Check for undeclared features in cfg attributes and macros
> (IGNORE) Several small CI improvements

- sdk/src/assertions/actions.rs
- sdk/src/assertions/creative_work.rs
- sdk/src/ingredient.rs
- sdk/src/manifest.rs
- sdk/src/resource_store.rs
Adds Ingredient::from_memory_async, from_stream_async and from_stream_info, set_memory_thumbnail
> Ingredient async and thumbnail support

- sdk/src/error.rs
- sdk/src/ingredient.rs
- sdk/src/manifest.rs
- sdk/src/resource_store.rs
returned if thumbnails or c2pa manifests are missing
reports the identifier or path of missing resource
_
> (MINOR) Added ResourceNotFound error

- sdk/src/ingredient.rs
- sdk/src/store.rs
While working on the Node.js SDK, I noticed that we were only listening to the `fetch_remote_manifests` flag when we were going through the file-based code path, not the in-memory ones. This attempts to make the remote fetching consistent whenever we try to load a store from a file, stream, or buffer.
> Make remote manifest handling consistent across input types

- sdk/src/asn1/rfc3161.rs
- sdk/src/store.rs
Restore fix to rfc3161.rs to properly decode Accuracy values.
> Fix timestamp Accuracy decoding

- sdk/src/manifest.rs
It looks like we were returning the data from the input stream in `embed_from_memory` instead of the data from the stream containing the embedded asset.
> Fix for returning input stream data when using `embed_from_memory`

- sdk/src/cose_sign.rs
This PR temporarily reverts the generation of 1.3 COSE headers until more client apps have been updated to the 1.3 spec.
> Generate old COSE headers for temporary backwards support

- sdk/src/asset_io.rs
I need to pass asset data across threads when working in the Node.js SDK due to how we need to offload computation off of the main thread. Since we operate off the `CAIRead` trait, we need to explicitly add the `Send` trait to allow this functionality.
> Add `Send` to `CAIRead` trait so that it can be used across threads

- sdk/src/assertions/mod.rs
Expose DataHash and BoxHash to public SDK
somehow I missed this on the previous release
> Expose DataHash and BoxHash to public SDK

- sdk/src/manifest_store_report.rs
This adds a convenience method for retrieving the certificate chain used to sign the active manifest from the bytes of the file containing the manifest.
> adds ManifestStoreReport::cert_chain_from_bytes

- README.md
- sdk/src/assertions/thumbnail.rs
- sdk/src/manifest.rs
When add_thumbnails is enabled, setting the manifest thumbnail format = "none" will force no claim thumbnail generation
> Adds a way to force no claim thumbnail generation

- sdk/src/assertions/bmff_hash.rs
- sdk/src/jumbf/boxes.rs
Fix issue found during interop testing where our safety checks were too strict.
> Fix for overly harsh checks when checking Merkle trees.

- README.md
Edits to README.md to update links to C2PA spec to v 1.3.
I double-checked that the links still worked correctly.
> Update links to C2PA spec to 1.3

- sdk/Cargo.toml
Temporary measure while we sort out integration issues with the openssl 3 integration that's in openssl-sys 0.9.93.
> Lock openssl-sys version to 0.9.92

- sdk/Cargo.toml
This appears to resolve a recently-introduced build error with the `actix::test` macro in the 0.13.0 release.
> Increase actix requirement to 0.13.1

- sdk/src/cose_validator.rs
This PR will allow Microsoft generated C2PA manifests to validate on Verify.  Note, this code will soon be replaced when we release Trust list support and its configuration store.
> Allow MS_C2PA_SIGNING OID to pass

- README.md
- sdk/src/asset_handlers/riff_io.rs
This was causing browser integrations to fail based on the detected MIME type for WAV files.
- Associate `audio/wav`, `audio/x-wav`, `audio/wave` and `audio/vnd.wave` as valid WAV MIME types based on [this comment](https://github.com/jshttp/mime-db/issues/22#issuecomment-107128888).
> Add all of the MIME types that are associated with WAV files

- README.md
- sdk/Cargo.toml
- sdk/src/assertions/box_hash.rs
- sdk/src/asset_handlers/jpeg_io.rs
- sdk/src/asset_handlers/riff_io.rs
Allow box hashing to contain arbitrary data between segments if they are contained within a range.
> Support for validating JPEGs that contain MPF (multi-picture format).

- sdk/src/claim.rs
- sdk/src/ingredient.rs
- sdk/src/jumbf/labels.rs
- sdk/src/manifest.rs
- sdk/src/resource_store.rs
- sdk/src/store.rs
- sdk/src/utils/mime.rs
- sdk/src/utils/mod.rs
Support databox thumbnails
Use jumbf uris for databox entries in manifeststore
[CAI-4141] always return application/c2pa for format instead of c2pa
Separates mime extension handling into a mime.rs utility.
> (MINOR) Support databox thumbnails CAI-4142

- .github/workflows/ci.yml
- sdk/src/claim.rs
(This supports an upcoming PR where I will need similar functionality for another assertion type.)
> (IGNORE) Refactor implementation of update_data_hash and update_bmff_hash

- sdk/src/asset_handlers/pdf.rs
- sdk/src/asset_handlers/pdf_io.rs
This is a small change that changes the value of the AF relationship key in the PDF's catalog from a reference to an array of references. This change was made because a PDF can have multiple associated files. The previous version assumed the c2pa file spec reference would be the only associated file.
> (PATCH) switches af relationship for a reference to the c2pa data to an array of references, one of which is the c2pa spec

- .github/workflows/ci.yml
Workaround for https://github.com/rust-lang/cargo/issues/12979.
> Disable Windows builds with latest Rust version

- make_test_images/Cargo.toml
- sdk/Cargo.toml
This should help resolve recent build failures on Windows.
> Update image crate dependency and limit features

- sdk/examples/data_hash.rs
- sdk/src/manifest.rs
- sdk/src/store.rs
Add RemoteSigner version for the data hash embeddable manifest case.
> Add support for embeddable manifests with RemoteSigner

- sdk/src/asset_handlers/pdf.rs
PDFs should be read from the EF/F embedded stream
> Fix PDF reading of manifest from wrong key

- sdk/src/claim.rs
Simpler version of Claim::update_assertion for simpler use cases.
> (IGNORE) Add crate private API Claim::replace_assertion

- deny.toml
- sdk/Cargo.toml
- sdk/src/asset_handlers/bmff_io.rs
- sdk/src/asset_handlers/jpeg_io.rs
- sdk/src/asset_handlers/mp3_io.rs
- sdk/src/asset_handlers/png_io.rs
- sdk/src/asset_handlers/riff_io.rs
- sdk/src/asset_handlers/svg_io.rs
- sdk/src/asset_handlers/tiff_io.rs
- sdk/src/asset_io.rs
NamedTempFile sets the windows Temp attribute, so clear it before renaming
> CAI-5041 Clear Windows temp attribute

- sdk/src/cose_sign.rs
1.3 moved certs to protected CoseSign1 headers.  Restore this functionality since clients have been updated
> Restore correct 1.3 CoseSign1 headers

- sdk/src/cose_sign.rs
- sdk/src/utils/test.rs
- add async_generic parameters to cose_sign::sign_claim
- update cose_sign::sign_claim to call cose_sign_async when the async version of the function is called
> Finish async signing implementation for cose_sign

- sdk/src/wasm/webpki_trust_handler.rs
Resolved a few errors that were happening on compilation to Wasm with regard to the `webpki_trust_handler` module.
> Add Wasm compilation fixes for trust_support branch

- sdk/src/ocsp_utils.rs
Use `.and_utc().timestamp()` instead.
> Fix use of deprecated method `chrono::NaiveDateTime::timestamp`

- sdk/Cargo.toml
Should fix the build issue with the minimum-direct-dependencies build.
> Update minimum dependency of rasn-* crates

- sdk/src/asset_handlers/c2pa_io.rs
- sdk/src/manifest.rs
- sdk/src/store.rs
> Adds a Manifest::composed manifest method

- sdk/Cargo.toml
- sdk/src/assertions/actions.rs
- sdk/src/manifest.rs
- sdk/src/settings.rs
There are no Rust APIS for this yet.
But it allows the values to pass through via actions.
This is a minimal change to allow the new actions. changes field to be set via JSON and read back that way.
Adding detailed Rust APIs should wait until the spec for this is completed
> Adds Action changes field as option vec of serde_json value

- sdk/src/store.rs
Change the api call of tempfile to fix the temp file is not auto deleted after the store save is completed.
The method [into_path](https://docs.rs/tempfile/latest/tempfile/struct.TempDir.html#method.into_path) will not delete temp file automatically, here should change to use method [path](https://docs.rs/tempfile/latest/tempfile/struct.TempDir.html#method.path) to access temp dir.
> Fixed temp file auto delete

- sdk/src/asset_handlers/bmff_io.rs
> Add `video/quicktime` to the list of BMFF MIME types

- .github/workflows/ci.yml
This runs `cargo test` instead of `codecov`, since `codecov` encounters issues running properly.
> Use cargo test in CI

- sdk/src/cose_sign.rs
- sdk/src/openssl/temp_signer_async.rs
- sdk/src/signer.rs
Updates ocsp_val in async signer to be async
> Async Signer: add support for async OCSP call

- make_test_images/src/make_test_images.rs
- sdk/examples/v2api.rs
- sdk/src/builder.rs
- sdk/src/lib.rs
- sdk/src/resource_store.rs
- sdk/tests/test_builder.rs
- sdk/tests/v2_api_integration.rs
Move signer to first parameter on Builder.sign. It makes sense for it always be the first paramter on signing operations.
> Move signer to first parameter on Builder.sign

- sdk/src/manifest.rs
- sdk/src/signer.rs
- sdk/src/store.rs
Support direct_cose_handling() on on all signing methods, sync and async.
Adds:
manifest.data_hash_embeddable_manifest_async
manifest.box_hash_embeddable_manifest_async.
We should be able to deprecate and then remote all RemoteSinger code once this is integrated.
> Steps toward removing RemoteSigner APIs.

- sdk/Cargo.toml
We need legal review on this license before we can accept it.
Related to https://github.com/servo/rust-url/pull/923
> url crate version 2.5.1 introduces new license "Unicode-3.0"

- sdk/Cargo.toml
- sdk/src/cose_validator.rs
This is a fix to a recent regression during validation.  We not validate the certificates contained in the OCSP response.  The certificates validity should be checked against the timestamp time vs the current time with stapled.
> OCSP certificate should be valid at signing time

- sdk/src/asset_handlers/bmff_io.rs
- sdk/src/asset_handlers/jpeg_io.rs
- sdk/src/asset_handlers/mp3_io.rs
- sdk/src/asset_handlers/png_io.rs
- sdk/src/asset_handlers/riff_io.rs
- sdk/src/asset_handlers/svg_io.rs
- sdk/src/asset_handlers/tiff_io.rs
- sdk/src/asset_io.rs
This PR changes the behavior of the `asset_io::rename_or_copy` function by deleting the copied file after it has been copied to the destination path.
This mainly affected our windows clients as the `std::fs::rename` fails when renaming a file from one drive to another drive on windows.
The new behavior is the following:
1. Atttempt to rename the file
2. If that fails, copy the file
3. If the copy succeeds, delete the temporary file.
> (PATCH) ensures temp files are removed

- README.md
- sdk/src/asset_handlers/mp3_io.rs
Adds XMP (remote manifest) support to MP3. Closes #367  
From XMP spec:
> Add remote manifest support to MP3

- sdk/src/assertion.rs
Temporarily comment `JsonAssertionData` to fix unused error in CI.
> Temporarily allow unused `JsonAssertionData` to fix unused error in CI

- sdk/src/asset_handlers/gif_io.rs
Set data box placeholder len to at least 1 for GIF. If not, the code errors [here](https://github.com/contentauth/c2pa-rs/blob/06bad589b7ec0538a76a4ee59bcfe7235495894a/sdk/src/assertions/data_hash.rs#L125) when writing to GIF.
~~TODO: does the placeholder box hash also need a len of at least 1?~~ Yes
> Set GIF data hash and box hash placeholder box len to >0

- sdk/src/assertions/metadata.rs
Fix for issue: https://github.com/contentauth/c2pa-rs/issues/504.  Incorrect serialization caused hash mismatch
> Make data_types field optional when serializing data-box-map

- sdk/src/ingredient.rs
- sdk/src/manifest.rs
Ensure Ingredient data_types are written to the ingredient assertion and are read back from it.
Add test cases to verity this.
> Ensure Ingredient data_types make it to the store and back.

- sdk/src/jumbf/boxes.rs
Fix for issue: https://github.com/contentauth/c2pa-rs/issues/515 where reading past a JUMBF box size was not considered an error.
> Make sure reading past end of JUMBF box is an error

- make_test_images/Cargo.toml
- make_test_images/src/make_thumbnail.rs
CI is breaking due to update in `image` crate, changing `io::Reader`->`::ImageReader`
> Fix CI tests

- sdk/Cargo.toml
Appears to be needed to compile with Rust 1.80
> Bump bcder minimum version to 0.7.3

- make_test_images/Cargo.toml
- sdk/Cargo.toml
- sdk/src/jumbf/boxes.rs
Fix issue reported in https://github.com/contentauth/c2patool/issues/173. This was caused by bug in x509_certificate crate
> Update crate to fix bad certificate dump content

- sdk/src/asset_handlers/gif_io.rs
GIF should copy the entire input stream to the output if no c2pa block was found when calling `remove_cai_store_from_stream`.
> Fix GIF `remove_cai_store_from_stream` behavior

- README.md
- sdk/src/lib.rs
Clarify use of unstable_api feature flag in README and examples.
> (IGNORE) Clarify use of unstable_api feature flag.

- sdk/src/assertions/mod.rs
- sdk/src/lib.rs
Export `AssertionDefinition` + `ActionTemplate` in public API.
> Export `AssertionDefinition` and `ActionTemplate` in public API

- export_schema/Cargo.toml
This is needed for
```
cargo install --git https://github.com/contentauth/c2pa-rs export_schema
```
to work, otherwise you get this error:
```
error[E0432]: unresolved import `c2pa::ManifestDefinition`
--> export_schema/src/main.rs:4:32
|
4   | use c2pa::{settings::Settings, ManifestDefinition, ManifestStore};
|                                ^^^^^^^^^^^^^^^^^^
|                                |
|                                no `ManifestDefinition` in the root
|                                help: a similar name exists in the module: `ManifestAssertion`
|
note: found an item that was configured out
--> /home/iameli/.cargo/git/checkouts/c2pa-rs-6dcfbef940eef094/345e24b/sdk/src/lib.rs:119:49
|
119 | pub use builder::{AssertionDefinition, Builder, ManifestDefinition};
| …
```
> export_schema: add unstable_api feature

- sdk/src/asset_handlers/riff_io.rs
When signing a remote manifest into a RIFF file and specifying a mime type (such as one derived from `crate::format_from_path`), RIFF will error with `UnsupportedType`. Currently, RIFF explicitly checks if the format passed was an extension (not mime type as well). We can either add the mime types to this check or remove the check completely (since all supported formats are handled the same anyways).
> Fix remote embedding RIFF when specifying mime type

- sdk/Cargo.toml
This was (inadvertently?) reverted to an older version in #529.
> (IGNORE) Re-upgrade async-generic to 1.1

- sdk/Cargo.toml
Should fix #571. (MSRV change and unfamiliar license added in 2.5.1 have been reverted.)
> Depend on url crate version 2.5.2 or newer

- sdk/src/cose_sign.rs
- sdk/src/cose_validator.rs
- sdk/src/openssl/ec_signer.rs
- sdk/src/utils/mod.rs
- sdk/src/utils/sig_utils.rs
If an external signer returns an EC signature in DER format convert it.
During validation return an error when we encounter an EC signature in the wrong format.
> EC signature DER support

- .github/workflows/ci.yml
Ironic: A test on the dependency infrastructure itself had an unneeded dependency.
> (IGNORE) Remove llvm-tools-preview component from minimal dependencies test

- sdk/src/status_tracker.rs
- sdk/src/store.rs
This PR requires `StatusTracker` implementations to implement the `Send` trait. This is required because c2pa-node is calling the function 
`Ingredient::from_manifest_and_asset_bytes_async`, which eventually calls `Store::ingredient_checks_async` in c2pa-rs. 
Marking the `Store::ingredient_checks_async` as not `Sync` with the `#[async_recursion(?Send)]` macro is preventing calls to `Store::ingredient_checks_async` with Tokio via the `tokio::spawn` function call. 
Another approach to this may be to only mark the `Store::ingredient_checks_async` 's status tracker argument, and all of its callers in c2pa-rs as `Send`. Something like this: `&mut (impl StatusTracker + Send)`.
> fix: requires "StatusTracker" to implement "Send"

- sdk/src/assertions/data_hash.rs
verify_hash was not respecting the value of the alg field.  Make sure it does.
> fix: Make sure algorithm is being respected in data_hash.rs

- CHANGELOG.md
- sdk/src/lib.rs
release-plz was unable to parse changelog for that reason.
> fix: Changelog contained duplicate entries for 0.16.1

- sdk/src/asset_handlers/bmff_io.rs
- sdk/src/asset_handlers/mp3_io.rs
- sdk/src/asset_handlers/png_io.rs
- sdk/src/asset_handlers/tiff_io.rs
- sdk/src/error.rs
- sdk/src/jumbf/boxes.rs
- sdk/src/utils/io_utils.rs
vec! will panic if the requested size is beyond the available memory limits.  This PR makes sure that user supplied values use a safer way to allocate than vec!.  It also adds a safe single line implementation of the common pattern:
let mut data = vec![0u8; data_len];
reader.read_exact(&mut data)?;
changes to:
let data = reader.read_to_vec(data_len)?;
> fix: Harden SDK against attempting buffers that are too large

- sdk/Cargo.toml
- sdk/src/assertions/actions.rs
- sdk/src/assertions/metadata.rs
- sdk/src/assertions/region_of_interest.rs
- sdk/src/builder.rs
fix: Adds identified RangeType to region of interest.
RangeType was missing the "identified' type now defined in the 2.1 spec, so this adds support for that type.
Also updated so that None fields in RegionOfInterest types do not serialize.
> fix: Adds identified RangeType to region of interest

- CHANGELOG.md
- cawg_identity/CHANGELOG.md
- crypto/CHANGELOG.md
- sdk/Cargo.toml
* `cawg-identity`: 0.1.0
* `c2pa-crypto`: 0.1.0
* `c2pa`: 0.37.0 -> 0.37.1 (✓ API compatible changes)
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
_24 October 2024_
* Create placeholders for forthcoming crates ([#645](https://github.com/contentauth/c2pa-rs/pull/645))
</blockquote>
<blockquote>
_24 October 2024_
* Create placeholders for forthcoming crates ([#645](https://github.com/contentauth/c2pa-rs/pull/645))
</blockquote>
<blockquote>
_24 October 2024_
* Update API documentation ([#621](https://github.com/contentauth/c2pa-rs/pull/621))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).
> chore: release

- cawg_identity/CHANGELOG.md
- cawg_identity/Cargo.toml
- crypto/CHANGELOG.md
- crypto/Cargo.toml
* `cawg-identity`: 0.1.0 -> 0.1.1 (✓ API compatible changes)
* `c2pa-crypto`: 0.1.0 -> 0.1.1 (✓ API compatible changes)
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
_24 October 2024_
* Tweak changelog format
</blockquote>
<blockquote>
_24 October 2024_
* Tweak changelog format
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).
> chore: release v0.1.1

- sdk/src/builder.rs
Fixed a typo in a docstring, from ClamDefinition to ClaimDefinition
> fix: Fixed a typo in ManifestDefinition docstring

- deny.toml
We should replace `instant` with `web_time` as called for in #663.
This is a temporary exemption for [RUSTSEC-2024-0384](https://rustsec.org/advisories/RUSTSEC-2024-0384).
> fix: Add temporary exemption for `instant` crate (no longer maintained)

- internal/crypto/src/time_stamp/mod.rs
- internal/crypto/src/time_stamp/provider.rs
- sdk/src/callback_signer.rs
- sdk/src/cose_sign.rs
- sdk/src/cose_validator.rs
- sdk/src/openssl/ec_signer.rs
- sdk/src/openssl/ed_signer.rs
- sdk/src/openssl/temp_signer_async.rs
- sdk/src/signer.rs
- sdk/src/store.rs
- sdk/src/time_stamp.rs
- sdk/src/utils/test.rs
- sdk/src/wasm/rsa_wasm_signer.rs
This causes problems with Python bindings that can't be addressed.
> fix: Remove `c2pa::Signer` dependency on `c2pa_crypto::TimeStampProvider`

- sdk/src/asset_handlers/jpeg_io.rs
Malformed jpeg may lead to insertion of CAI data at invalid index
> fix: JPEG `write_cai` OOB insertion

- sdk/src/asset_handlers/svg_io.rs
Use saturating sub to prevent negative length value.
> fix: Prevent negative length value for SVG object locations

- internal/crypto/src/raw_signature/mod.rs
- internal/crypto/src/raw_signature/validator.rs
- internal/crypto/src/webcrypto/async_validators/ecdsa_validator.rs
- internal/crypto/src/webcrypto/async_validators/ed25519_validator.rs
- internal/crypto/src/webcrypto/async_validators/mod.rs
- internal/crypto/src/webcrypto/async_validators/rsa_legacy_validator.rs
- internal/crypto/src/webcrypto/async_validators/rsa_validator.rs
- internal/crypto/src/webcrypto/mod.rs
(When OpenSSL is used, it's just a wrapper around the synchronous code path.)
> feat: Make `AsyncRawSignatureValidator` available on all platforms

- internal/crypto/src/cose/mod.rs
- internal/crypto/src/cose/sign.rs
- internal/crypto/src/cose/sigtst.rs
- internal/crypto/src/cose/time_stamp_storage.rs
- internal/crypto/src/cose/verifier.rs
- internal/crypto/src/openssl/check_certificate_trust.rs
- internal/crypto/src/time_stamp/mod.rs
- internal/crypto/src/time_stamp/response.rs
- internal/crypto/src/webcrypto/async_validators/ecdsa_validator.rs
- sdk/src/cose_sign.rs
- sdk/src/store.rs
- sdk/src/utils/test.rs
Review #707 for changes that should be incorporated into `c2pa_crypto` crate.
The biggest change is the introduction of the `TimeStampStorage` enum, which can select V1 (now deprecated) or V2 (new as of C2PA 2.x) handling of `sigTst` or `sigTst2` time stamp headers.
> fix: Bring `claim_v2` changes from #707 into `c2pa_crypto`

- .github/workflows/ci.yml
The `cargo-udeps-action` has not been updated in more than a year and no longer operates on GitHub's Ubuntu runner.
> chore: Install `cargo udeps` directly rather than using action

- cawg_identity/Cargo.toml
- cli/Cargo.toml
- export_schema/Cargo.toml
- internal/crypto/Cargo.toml
- internal/status-tracker/Cargo.toml
- make_test_images/Cargo.toml
- sdk/Cargo.toml
See https://github.com/est31/cargo-udeps/issues/293, related to https://github.com/rust-lang/rust/pull/131729.
> chore: Work around new issue with `#[cfg(test)]`

- Cargo.lock
- cawg_identity/Cargo.toml
- cawg_identity/src/builder/credential_holder.rs
- cawg_identity/src/builder/error.rs
- cawg_identity/src/builder/mod.rs
- cawg_identity/src/tests/builder/error.rs
- cawg_identity/src/tests/builder/mod.rs
- cawg_identity/src/tests/fixtures/mod.rs
- cawg_identity/src/tests/fixtures/naive_credential_holder.rs
- cawg_identity/src/tests/mod.rs
Includes `NaiveCredentialHolder` implementation to be used in test cases only.
Split off from #644.
> feat(cawg_identity): Define `CredentialHolder` trait

- sdk/src/asset_handlers/tiff_io.rs
- sdk/src/jumbf_io.rs
Writers of native formats cannot be easily tested and are beyond the scope of the SDK.
> feat: Remove writing of native camera RAW formats from SDK

- sdk/src/builder.rs
- sdk/src/dynamic_assertion.rs
- sdk/src/utils/test.rs
- sdk/src/utils/test_signer.rs
Also: Fix several WASM platform build issues introduced recently.
> chore(sdk): Remove `Send` and `Sync` bounds from `DynamicAssertion` on WASM

- internal/crypto/src/cose/verifier.rs
- internal/crypto/src/raw_signature/mod.rs
- internal/crypto/src/raw_signature/validator.rs
- internal/crypto/src/raw_signature/webcrypto/check_certificate_trust.rs
- internal/crypto/src/tests/raw_signature/async_validators.rs
- internal/crypto/src/tests/raw_signature/mod.rs
The wrapper was causing more problems than it was worth.
> fix(crypto): Disable the built-in async validators on non-WASM platforms

- cawg_identity/src/tests/fixtures/test_credentials.rs
- internal/crypto/src/raw_signature/signing_alg.rs
- sdk/src/utils/test_signer.rs
Make alg enum exhaustive, so it can be understood by other tools too.
Build issue this fixes: https://github.com/contentauth/c2pa-python/pull/82
Also reported in https://github.com/mozilla/uniffi-rs/issues/2414
> fix: Make alg enum exhaustive

- cawg_identity/src/builder/identity_assertion_signer.rs
- cli/src/callback_signer.rs
- internal/crypto/src/raw_signature/signer.rs
- sdk/src/callback_signer.rs
- sdk/src/cose_sign.rs
- sdk/src/cose_validator.rs
- sdk/src/signer.rs
- sdk/src/store.rs
- sdk/src/utils/test.rs
- sdk/src/utils/test_signer.rs
Removes the need for each `Signer` implementation to also provide `RawSigner` and `TimeStampProvider` implementations.
> feat: Change the definition of `Signer.raw_signer()` to return an `Option` defaulting to `None`

- internal/crypto/Cargo.toml
- sdk/Cargo.toml
Needed because c2pa-crypto refers to the `tbs_data` method which was made public in 0.3.8.
> fix: Bump coset requirement to 0.3.8

- sdk/src/manifest.rs
- sdk/src/manifest_store.rs
- sdk/src/manifest_store_report.rs
- sdk/tests/integration.rs
Cargo test was broken after recent checkin, this fixes it.
> fix: repair cargo test

- internal/crypto/src/cose/sign.rs
- internal/crypto/src/ec_utils.rs
This PR adds support to handle incorrect EC signers with ability to handle arbitrary curves.
> fix:  P1363 fix to handle incorrect signers

- Cargo.lock
- cawg_identity/src/internal/debug_byte_slice.rs
Workaround for https://github.com/release-plz/release-plz/issues/2034.
> fix(cawg_identity): No-op change to trigger re-release of cawg-identity crate

- sdk/src/jumbf_io.rs
While using this function, I noticed that it takes an explicit `&Path`, which isn't as ergonomic as it could be. All of the functions in [`std::fs`][0] use `AsRef<Path>`, which means that this function could easily take strings as well.
[0]: https://doc.rust-lang.org/stable/std/fs/index.html
I see most of the `from_file()` functions already use `AsRef<Path>`, so this is more of a consistency PR than anything. I think there are still a few occurrences of `&Path` I didn't change; I'm happy to do so, just figured I would start the discussion with this PR.
> refactor: use `AsRef<Path>` in `load_jumbf_from_file()`

- cawg_identity/src/builder/identity_assertion_builder.rs
- sdk/src/dynamic_assertion.rs
- sdk/src/lib.rs
- sdk/src/store.rs
- sdk/tests/test_builder.rs
This allows DynamicAssertions to create JSON formatted assertions. Previously only Cbor formatted assertions were supported.
> feat: Add support for DynamicAssertions in JSON format

- Cargo.lock
- cli/Cargo.toml
- sdk/src/asset_handlers/jpeg_io.rs
> chore: bump c2patool version

- .github/workflows/beta-preflight.yml
- sdk/src/assertion.rs
- sdk/src/manifest_store.rs
- sdk/src/manifest_store_report.rs
- sdk/src/settings.rs
Also: Add new GitHub Action to preflight build with future Rust betas.
This should help us anticipate and fix issues when a new Rust stable build is expected.
> fix: Fix new Clippy warnings for Rust 1.85.0

- Cargo.lock
- internal/crypto/Cargo.toml
- sdk/Cargo.toml
x509-certificate v0.22.0 uses a newer version of ring (0.17.5) which cannot be built by Xcode on Mac Silicon for wasm32-unknown-unknown.
> fix: Use older version of x509-certificate for wasm32-unknown

- cawg_identity/src/identity_assertion/assertion.rs
- make_test_images/src/compare_manifests.rs
- sdk/src/builder.rs
- sdk/src/claim.rs
- sdk/src/ingredient.rs
- sdk/src/jumbf_io.rs
- sdk/src/lib.rs
- sdk/src/manifest_store.rs
- sdk/src/manifest_store_report.rs
- sdk/src/reader.rs
- sdk/src/store.rs
- sdk/src/validation_results.rs
- sdk/src/validation_status.rs
- sdk/tests/common/compare_readers.rs
- sdk/tests/test_builder.rs
This is also a cleanup of the new API, removing ManifestStore, ManifestStoreReport, and Store from the public API unless the v1_api feature is used.
These are steps toward a version 1.0 SDK.
> feat: Adds validation_state to the json reports from the Reader

- internal/crypto/README.md
- internal/crypto/src/raw_signature/rust_native/signers/ecdsa_signer.rs
- internal/crypto/src/raw_signature/rust_native/signers/mod.rs
- internal/crypto/src/tests/cose/certificate_trust_policy.rs
- sdk/Cargo.toml
- sdk/src/builder.rs
With this change the only signature implemented in OpenSSL but not native Rust is ES512. This is important for wasm and embedded use cases.
> feat: Add ES256 and ES384 Rust native signing

- .github/workflows/ci.yml
- Cargo.lock
- Makefile
- cawg_identity/Cargo.toml
- cawg_identity/README.md
- cawg_identity/src/claim_aggregation/w3c_vc/did_web.rs
- cawg_identity/src/tests/builder/error.rs
- cawg_identity/src/tests/builder/simple_case.rs
- cawg_identity/src/tests/claim_aggregation/interop.rs
- cawg_identity/src/tests/claim_aggregation/w3c_vc/did.rs
- cawg_identity/src/tests/claim_aggregation/w3c_vc/did_buf.rs
- cawg_identity/src/tests/claim_aggregation/w3c_vc/did_web.rs
- cawg_identity/src/tests/claim_aggregation/w3c_vc/jwk.rs
- cawg_identity/src/tests/identity_assertion/signer_payload.rs
- cawg_identity/src/tests/internal/debug_byte_slice.rs
- cawg_identity/src/tests/mod.rs
- cawg_identity/src/tests/x509.rs
- sdk/src/store.rs
Add WASI support to cawg_identity
> feat: Add WASI support to cawg_identity

- .github/workflows/ci.yml
- Cargo.lock
- Makefile
- cli/Cargo.toml
- cli/docs/usage.md
- cli/src/callback_signer.rs
- cli/src/main.rs
- cli/src/signer.rs
- cli/tests/integration.rs
- sdk/src/store.rs
The wasm created for wasm32-wasip2 can be run directly with [wasmtime](https://docs.wasmtime.dev/). It also can be transpiled to a JS + core Wasm for JavaScript execution using [jco](https://bytecodealliance.github.io/jco/transpiling.html).
> feat: Add WASI to c2patool

- sdk/src/dynamic_assertion.rs
Add sync trait to AsyncDynamicAssertion
Required for V24 node SDK.
> feat: Add `Sync` to `AsyncDynamicAssertion`

- Cargo.lock
- cli/Cargo.toml
Removes dependency on humantime crate, which is no longer maintained.
> update: Bump env_logger from 0.11.6 to 0.11.7

- sdk/src/asset_handlers/jpeg_io.rs
As #967 states, this removes the ReSTart 0 through 7 segment markers from the `has_length` check. As these markers are standalone markers and do not have a 2-byte length specified after them.
> fix: ISSUE-967: Remove the `RST0..=RST7` check from the `has_length` method for the JPEG asset handler.

- internal/crypto/src/cose/mod.rs
- internal/crypto/src/cose/sign.rs
This API takes a new `CosePayload` enum parameter which can be configured to allow the COSE payload to include or exclude the payload as appropriate for the use case.
> feat(crypto): Add new `sign_v2_embedded` API

- Cargo.lock
- cawg_identity/Cargo.toml
- cli/Cargo.toml
- sdk/Cargo.toml
c2patool and cawg_identity won't publish to crates.io unless c2pa_rs is updated, so this updates c2pa_rs sdk to force that publish (hopefully)
> chore: publish c2patool and cawg_identity updates

- internal/crypto/src/raw_signature/rust_native/check_certificate_trust.rs
The full list of certs should be used to check the complete build chain.  This will allow for chains with only the end-entity cert to be verified against a set of anchors. 
> fix: Use correct list so that empty cert chains are processed

- Cargo.lock
- cawg_identity/Cargo.toml
- cawg_identity/examples/cawg.rs
We lost this example due to circular dependencies, so this puts it back in. I set it up in a higher level examples folder so that it can be executed with cargo run --example cawg source.ext dest.ext
> chore: Add a CAWG X.509 signing example

- README.md
As discussed, some links in the README are broken on https://crates.io/crates/c2pa. I fixed the broken links by either:
- Changing to an absolute GitHub URL, for links that will be show only on crates.io and GitHub (in the intro para, which is not displayed on the doc site).
- Changing to an absolute URL on https://opensource.contentauthenticity.org/docs (elsewhere on the page, which is displayed on the doc site).
> docs: Fix links that are broken on crates.io

- sdk/src/claim.rs
- sdk/src/jumbf/labels.rs
- sdk/src/manifest.rs
- sdk/src/utils/test.rs
Make sure users supplied manifests labels conform and allow support for Claim V2 labels.
> fix: Fix support for user supplied labels

- sdk/src/settings.rs
This change makes settings definable per thread.
> fix: Thread safe version of settings.rs

- sdk/src/asset_handlers/bmff_io.rs
- sdk/src/cose_sign.rs
- sdk/src/cose_validator.rs
- sdk/src/ingredient.rs
- sdk/src/manifest_store.rs
- sdk/src/reader.rs
- sdk/src/settings.rs
- sdk/src/store.rs
This PR turns on trust list check for all unit test expect those where we do not have access to the source certificate.
> fix: Enable trust checks for all unit tests

- Cargo.lock
- internal/crypto/src/cose/verifier.rs
- internal/status-tracker/src/validation_codes.rs
- sdk/src/claim.rs
- sdk/src/ingredient.rs
- sdk/src/store.rs
- sdk/src/validation_results.rs
- sdk/src/validation_status.rs
- sdk/tests/test_failures.rs
Timestamp errors are now informational
maps error & informational codes from from v1 claim ingredients Added timestamp.malformed informational status.
signature errors have correct urls
chore :  update yanked crate
updated timestamp unit tests for informational status
> fix: dup check with validation kind

- cli/README.md
Removes outdated instructions to install c2patool using `cargo binstall`.
Closes #742.
> docs: Remove instructions to install c2patool using binstall

- cawg_identity/src/builder/identity_assertion_builder.rs
- cawg_identity/src/builder/mod.rs
- cawg_identity/src/x509/x509_credential_holder.rs
Due to Node.js's memory management, many cawg identity traits need to be reimplemented in the c2pa-bindings Node.js SDK.
* Export finalize_identity_assertion
* Add Send + Sync to CredentialHolder
> feat: Changes required for Node SDK with Neon

- README.md
- docs/release-notes.md
Update docs to discourage production use of 2.1 claims for now, per discussion.
> docs: Emphasize, clarify and add more re v2 claims

- Cargo.lock
- cli/Cargo.toml
- cli/src/main.rs
Verified with:
`wasmtime -S cli -S http --dir . --dir cawg_identity/src/tests/fixtures/claim_aggregation target/wasm32-wasip2/debug/c2patool.wasm cawg_identity/src/tests/fixtures/claim_aggregation/adobe_connected_identities.jpg`
> fix: enable post_validate_async for WASI

- sdk/src/builder.rs
- sdk/src/ingredient.rs
Builder::add_stream was lot fetching remote ingredient manifests when that feature is enabled.
This corrects that and adds a test for it.
> fix: Ingredient from_stream/memory not loading remote manifests

- README.md
- cli/CHANGELOG.md
- cli/README.md
- cli/docs/release-notes.md
The C2PA Tool release notes have not been updated for a long time (since v 0.9), and the CHANGELOG really contains the most recent release notes.  This is already reflected in the [open source doc site](https://opensource.contentauthenticity.org/docs/c2patool-rns).
This PR changes links to point to the CHANGELOG instead of the old release notes, and adds a small caveat to the top of the (old) release notes,  along with a few other minor tweaks.
> docs: Replace old c2patool release notes with CHANGELOG

- .commitlintrc.yml
- docs/release-process.md
Per feedback on https://github.com/contentauth/c2pa-rs/pull/1057#discussion_r2067457725, relaxing restrictions on commit description format.
> chore: Remove description format enforcement from .commitlintrc.yml

- Cargo.lock
- c_api/Cargo.toml
- sdk/Cargo.toml
Appears the major version bump (2.6.1 -> 3.0.0) was triggered by removal of a crate feature that we weren't using. Other changes appear minimal.
> fix: Switch zip dependency to a non-yanked version

- .github/workflows/ci.yml
- c_api/Cargo.toml
- cli/Cargo.toml
- export_schema/Cargo.toml
- make_test_images/Cargo.toml
- sdk/Cargo.toml
- sdk/src/crypto/cose/certificate_trust_policy.rs
- sdk/src/crypto/raw_signature/mod.rs
- sdk/src/crypto/raw_signature/rust_native/signers/mod.rs
- sdk/src/crypto/raw_signature/signer.rs
- sdk/src/crypto/raw_signature/tests/async_signers.rs
- sdk/src/crypto/raw_signature/tests/signers.rs
- sdk/src/crypto/raw_signature/tests/validators.rs
- sdk/src/crypto/raw_signature/validator.rs
- sdk/src/ingredient.rs
- sdk/src/lib.rs
Openssl will not be included when building rust native crypto
CI tests for both openssl and rust_native_crypto features
> feat: Make OpenSSL a default feature

- Cargo.lock
- Cargo.toml
- c_api/Makefile
The workspace version from my branch wasn't updated to 0.53.0, this fixes that.
> build: restore correct version at workspace level

- release-plz.toml
I renamed the internal c2pa-c match the c_api folder name, but I didn't update release-plz to know about the name change.
> build: update release-plz for c_api name.

- README.md
- cli/README.md
- docs/cawg-identity.md
- Change some links to absolute URLs so they work everywhere
- Add minimall Rust installation instructions
- Move note about CAWG assertion limitations to doc on CAWG
> docs: Doc cleanup

- Cargo.lock
- sdk/Cargo.toml
Temporary fix until we review c2pa-rs MSRV.
> fix: Freeze base64ct crate at 1.7.3 for now

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- c2pa_c_ffi/CHANGELOG.md
- c2pa_c_ffi/Cargo.toml
- cli/Cargo.toml
- macros/CHANGELOG.md
* `c2pa`: 0.56.0 -> 0.56.1 (✓ API compatible changes)
* `c2pa-c-ffi`: 0.56.0 -> 0.56.1
* `c2pa_macros`: 0.56.0 -> 0.56.1
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
_18 June 2025_
* To_archive does not store resources associated with ingredients ([#1151](https://github.com/contentauth/c2pa-rs/pull/1151))
</blockquote>
<blockquote>
_18 June 2025_
* Rename c_api to c2pa_c_ffi and publish ([#1159](https://github.com/contentauth/c2pa-rs/pull/1159))
* Add required entries to Cargo.toml ([#1166](https://github.com/contentauth/c2pa-rs/pull/1166))
* Fix c2pa_c_ffi Cargo.toml to allow `cargo publish` to succeed ([#1164](https://github.com/contentauth/c2pa-rs/pull/1164))
</blockquote>
<blockquote>
_18 June 2025_
* Update Validation for 2.2 spec compliance …
> chore: release v0.56.1

- Cargo.toml
- c2pa_c_ffi/Cargo.toml
- c2pa_c_ffi/README.md
- Build target changes so that C FFI API may be usable in other Rust projects too
> feat: C FFI API should be usable in other Rust projects too

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- c2pa_c_ffi/CHANGELOG.md
- c2pa_c_ffi/Cargo.toml
- cli/Cargo.toml
* `c2pa`: 0.56.2 -> 0.57.0 (✓ API compatible changes)
* `c2pa-c-ffi`: 0.56.2 -> 0.57.0
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
_19 June 2025_
* No-op change to trigger c2pa core crate publish
</blockquote>
<blockquote>
_19 June 2025_
* C FFI API should be usable in other Rust projects too ([#1173](https://github.com/contentauth/c2pa-rs/pull/1173))
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/release-plz/release-plz/).
> chore: release v0.57.0

- c2pa_c_ffi/Makefile
The dylib / dlls in the deps file were being copied to the zip output instead of the artifacts in the release folder. This was messing up the paths in the dylibs as we were converting the paths to relative paths in the dylibs, using install_name_tool, in the release folder, then copying the dylibs from the deps folder (where the paths were not updated)  into the zip during release.
> chore: ensures dylib in release folder is copied

- .github/workflows/ci.yml
* Set longer timeout
* Use Chrome for testing version 137 to show output
* Explicitly set chrome-driver to use
> fix: Fix wasm-pack yet again

- Cargo.lock
- sdk/Cargo.toml
This PR bumps the version of `nonempty-collections` in use, as it was two major versions behind.
> chore: Bump `nonempty-collections` to current version

- sdk/src/assertions/uuid_assertion.rs
- sdk/src/asset_handlers/svg_io.rs
- sdk/src/crypto/ec_utils.rs
- sdk/src/dynamic_assertion.rs
- sdk/src/identity/claim_aggregation/w3c_vc/did.rs
- sdk/src/ingredient.rs
- sdk/src/manifest.rs
- sdk/src/resource_store.rs
- sdk/src/utils/cbor_types.rs
Updating syntax ahead of new `mismatched-lifetime-syntaxes` lint rule hitting stable.
https://github.com/rust-lang/rust/pull/138677
> chore: upcoming clippy fixes

- sdk/src/asset_handlers/bmff_io.rs
Add m4v and its mimetype to list of support BMFF format
> fix: Add support for m4v

- Cargo.lock
- cli/Cargo.toml
`async-std` is a rather large unused dependency of `c2patool`. This PR removes it.
> chore: remove unused `async-std` dependency from `c2patool`

- .github/workflows/ci.yml
- Makefile
- sdk/Cargo.toml
- sdk/src/builder.rs
- sdk/src/identity/tests/claim_aggregation/validation.rs
- sdk/src/lib.rs
- sdk/src/store.rs
- sdk/tests/test_reader.rs
Enable feature `fetch_remote_manifests` for wasm-bindgen
> feat: browser wasm fetch remote manifests

- sdk/examples/client/client.rs
- sdk/examples/data_hash.rs
- sdk/src/assertions/creative_work.rs
- sdk/src/assertions/mod.rs
- sdk/src/assertions/schema_org.rs
- sdk/src/builder.rs
- sdk/src/manifest.rs
CreativeWork assertion is no longer part of the C2PA Technical Specification and its use should be avoided when creating new manifests.
> fix: Mark the CreativeWork assertion as deprecated

- sdk/src/assertions/labels.rs
- sdk/src/assertions/metadata.rs
- sdk/tests/test_builder.rs
Adds CAWG_METADATA
label and a unit test to ensure it works ok.
We should add a full example later.
> feat: add cawg.metadata label and test.

- sdk/tests/integration.rs
Fetching OCSP status for certificates has not yet been implement in wasm, therefore the test in question was failing.
> chore: skip OCSP check for wasm in test

- deny.toml
See #1351, which asks that we update httpmock as soon as an update is available.
> chore: Temporarily allow async-std crate, despite its unmaintained status

- sdk/src/identity/validator.rs
- sdk/src/store.rs
CawgValidate should not return errors since it will log.
> fix: rewind output  stream after adding dynamic assertions

- Cargo.lock
- sdk/Cargo.toml
Random number generation now works without specifying dependencies for Wasm.
> chore: update uuid

- sdk/src/crypto/raw_signature/openssl/validators/rsa_validator.rs
This PR brings c2patool in line with how the current Verify/Inspect sites perform.  It removes the RSA-PSS automatic salt detection performed by OpenSSL in favor of what is specified in the Cose [spec](https://datatracker.ietf.org/doc/html/rfc8230/#section-2).
> fix: Make OpenSSL code path enforce COSE specified salt length

- sdk/src/assertions/assertion_metadata.rs
The AssertionMetadata field "localizations" is in the spec but was missing from our implementation. It is now added and supported.
> fix: assertion metadata localizations support was missing. CAI-9444

- cli/src/main.rs
It's currently not possible to pass in an external manifest to `c2patool`. This is useful if a manifest was acquired through means such as a network call externally. This PR adds a new argument `--external-manifest` (open to opinions) to pass in an external manifest during validation.
* Closes #1353
> feat: allow specifying external binary manifest to `c2patool`

- cli/docs/usage.md
Documents the new `--external-manifest` c2patool argument in the `usage.md`.
> docs: document `--external-manifest` c2patool argument

- sdk/Cargo.toml
This PR disables the “asm” feature of sha2 for AArch64 Windows. Windows aarch64 builds are failing internally because of this feature.
> fix: only enable "asm" feature on aarch64 macos

- .github/workflows/library-release.yml
- c2pa_c_ffi/Makefile
- make_release.ps1
I thought caching was the issue that corrupts the Windows libraries. I removed caching in this PR: https://github.com/contentauth/c2pa-rs/pull/1422. I believe that hypothesis has been proven wrong, as I observed one more corruption in the latest release.
So I continued looking into this. I wanted to check how the Windows ARM files look, since Win ARM is also in the build matrix. But there were none on the release page (for WinARM, only Intel). It turns out, that we attempt a build for Windows ARM, and the build script (make_release.ps1) detects the CPU architecture to put it in the name. For both targets, if detects x86_64 (Intel) architecture, and does not cross-compile. I now believe that those two builds running in parallel override each other's zips on the last upload (since they do …
> fix: Fix ARM builds

- Cargo.lock
- sdk/Cargo.toml
- sdk/src/assertions/actions.rs
`serde` was recently updated to allow fields in a struct/enum to be marked as deprecated without always outputting usage of a deprecated field warning. This is a small change to fix that issue with `DigitalSourceType`.
> fix: mark `DigitalSourceType` fields as deprecated without warning (new serde update)

- Cargo.lock
- cli/Cargo.toml
- deny.toml
- sdk/Cargo.toml
This update also significantly reduces the dependency footprint of httpmock as seen with the amount of changes in the Cargo.lock.
Closes #1351
> build: Update httpmock to 0.8.0

- sdk/src/lib.rs
Latest build of ours docs is failing due to removed Rust features. This PR removes those features that have now been merged into the `doc_cfg` feature.
See logs here: https://docs.rs/crate/c2pa/0.67.1/builds/2553949
> docs: fix docs.rs build by removing removed features
