Makefile
Add Makefile for local testing
* make test -- full validation and test all features including WASM 
* make doc -- build and view docs
* make images -- create test images in target/test-images
* make client -- run the client example with a sample source file
* make c2patool-release -- build c2patool zip distribution with app, samples and readme
=> Add Makefile for local testing

.github/workflows/publish.yml
Adds c2patool crate to build automation.
=> Publish c2patool crate

c2patool/Cargo.toml, c2patool/src/main.rs, c2patool/src/signer.rs, c2patool/tests/integration.rs, make_test_images/src/make_test_images.rs, sdk/examples/client/client.rs, sdk/src/assertions/actions.rs, sdk/src/assertions/creative_work.rs, sdk/src/lib.rs, sdk/src/manifest.rs, sdk/src/manifest_assertion.rs, sdk/src/store.rs, sdk/src/utils/test.rs, sdk/tests/integration.rs
Update ManifestAssertion supporting instances
=> (MINOR) Update ManifestAssertion supporting instances

.github/workflows/publish.yml
=> Remove cargo edit from publish workflow

sdk/src/store.rs
The buffer was point to wrong point to be able to verify.  Should point to raw data.
- [ x] This PR represents a single feature, fix, or change.
- [x ] All applicable changes have been documented.
- [x ] Any `TO DO` items (or similar) have been entered as GitHub issues and the link to that issue has been included in a comment.
=> Fix bug in verify_from_buffer

.github/workflows/publish.yml, CHANGELOG.md, README.md
Also, one more minor bug in CHANGELOG formatting.
=> Fix bug in updating crate reference in README

README.md
Fix a grammatical error introduced when we split off c2patool into its own repo.
=> (IGNORE) Fix a typo in README

README.md
=> (IGNORE) Add docs.rs badge with link to latest documentation

sdk/src/claim.rs, sdk/src/cose_validator.rs
If there is no timestamp that is not an error.
=> Fix bad response for case when there is no timestamp

make_test_images/src/make_test_images.rs
make_test_images was not using tsa_url, fix so that it does
=> Update `make_test_images` to use timestamp authority

README.md, sdk/src/lib.rs
Clarify when you need to add dependencies to Cargo file, per #92.
=> (IGNORE) Clarify dependency requirements

sdk/src/ingredient.rs
Bug fix: Ingredients with valid claims not reporting correct thumbnails
This was an issue in ManifestStore::from_file / bytes
also fixed minor issue with not detecting a valid png thumbnail existing in an added ingredient.
=> Bug fix: Ingredients with valid claims not reporting correct thumbnails

sdk/src/cose_sign.rs
Fix sign_claim to not mask errors
=> Fix for `sign_claim` masking error

sdk/src/asset_handlers/bmff_io.rs, sdk/src/cose_sign.rs
Support for more BMFF container types
Handle bad FourCC names
Add bad signer unit test
Minor bug fixes and enhancements found during external manifest work.  While testing BMFF data found some needed 
enhancements.  Added unit test for bad signer.
=> Treat 'meta' box as standard container

CHANGELOG.md
=> Remove inadvertent 1.0.0 release from changelog

sdk/Cargo.toml
While building other projects for other targets sometimes could not link.  This is a offers a more general solution that should build everywhere.
=> (MINOR) Switch to "lib" for crate-type

.github/workflows/ci.yml
Looks like there's a compatibility issue that needs resolving in cargo-semver-check crate.
Restore when https://github.com/obi1kenobi/cargo-semver-check/issues/122 is fixed.
=> (IGNORE) Disable cargo-semver-checks step

sdk/examples/client/client.rs, sdk/src/assertions/exif.rs, sdk/src/assertions/mod.rs, sdk/src/manifest.rs
Adds basic Exif Assertion support
=> Add Exif Assertion support

README.md
Correct outdated statement of support file formats, and link to table in c2patool instead. 
- [x ] This PR represents a single feature, fix, or change.
- [x ] All applicable changes have been documented.
=> [IGNORE] Update README

.github/workflows/ci.yml, .github/workflows/publish.yml
Adapted from https://github.com/adobe/xmp-toolkit-rs
* Build crate 3x/week and alert on error
* Include recommended fix for CodeCov flakiness
* Simplify semver check
* Add notes about warnings in publish workflow
=> Build infrastructure improvements

.github/workflows/ci.yml, .github/workflows/publish.yml
Addresses some deprecation warnings during our PR validation and crate publish workflows
=> (IGNORE) Update semantic-version GitHub action

sdk/src/manifest_store.rs, sdk/src/resource_store.rs
Fixed unit test failure (invalid unique name generation)
=> Fixed unit test failure (invalid unique name generation).

sdk/Cargo.toml
Avoids a security vulnerability
=> Avoid chrono's transitive dependency on time crate

.github/workflows/ci.yml, README.md
(Adapted from similar support recently added to XMP Toolkit.)
=> Add support for ARM on Linux

sdk/src/ingredient.rs
Fixes an injected bug causing Ingrdient_from_file /stream to fail
=> Fixes bug in Ingredient_from_stream_info

README.md, sdk/Cargo.toml
Bumps the minor version and adds a new Readme section on changes.
=> Bump minor version and update README.md

README.md
Force minor version change to 0.24.0
=> (MINOR) force minor version change

.github/workflows/ci.yml, make_test_images/Cargo.toml, sdk/Cargo.toml
Update CI unit test minimum to 1.7
revert image version
enforce half version
=> Repair CI tests

sdk/src/manifest.rs, sdk/src/store.rs, sdk/src/utils/test.rs
Converts DataHash and BoxHash methods to use RemoteSigner instead of AsyncSigner
=> (MINOR) Converts DataHash and BoxHash methods to use RemoteSigner instead of AsyncSigner

.github/workflows/nightly.yml, README.md
Create nightly build branch that can be used for testing downstream builds
=> (IGNORE) Create new nightly build task

sdk/examples/data_hash.rs, sdk/src/lib.rs, sdk/src/manifest.rs, sdk/src/manifest_store.rs, sdk/src/store.rs
Expose HashRange to help with external hash generation. 
Added new examples for external manifest generation,
Changed embedded manifest functions to be synchronous to better match their use case.
=> (MINOR) Expose HashRange

sdk/src/asset_handlers/mp3_io.rs
(NOTE: This targets existing PR #295.)
=> Avoid extra allocations

.github/workflows/ci.yml, .github/workflows/publish.yml, .gitignore
This is much MUCH faster than the v1 we were using previously
=> (IGNORE) Update to cargo-semver-checks-action v2

sdk/src/utils/hash_utils.rs
Fix build issue with Blake3 code
=> Blake build fix

.gitignore, sdk/src/error.rs, sdk/src/wasm/webpki_trust_handler.rs
=> Small fixes for Wasm building

sdk/src/asset_handlers/tiff_io.rs, sdk/src/store.rs
Support for ARW and NEF raw formats is enabled.
=> Add support for ARW and NEF

sdk/Cargo.toml, sdk/src/openssl/rsa_signer.rs, sdk/src/openssl/rsa_validator.rs
Update to OpenSSL 3 and compatibility fixes
=> Openssl update to version 3.x

sdk/src/assertions/box_hash.rs, sdk/src/claim.rs, sdk/src/validation_status.rs
=> Fix response strings for BMFF and Box hash statuses

sdk/src/asset_handlers/pdf.rs
Nightly has improved dead code analysis. This pr allows `dead_code` in the PDF module until we can finish the PDF work.
=> allows builds to pass

sdk/src/cose_validator.rs
"Supported Valiators" --> "Supported Validators" in a code comment.
=> Fixed typo in comment

sdk/src/manifest.rs
Returns the remote url used when
building a manifest.
This is always None when reading existing manifests.
part of a fix for CAI-5437
=> Adds Manifest.remote_manifest_url() (CAI-5437)

sdk/src/trust_handler.rs
Adds Send trait to TrustHandlerConfig
=> (MINOR) Adds Send trait to TrustHandlerConfig

sdk/src/asset_handlers/jpeg_io.rs, sdk/src/utils/xmp_inmemory_utils.rs
This works without xmp_toolkit
=> Implements embed_reference_to_stream for jpeg

sdk/src/asset_handlers/bmff_io.rs, sdk/src/jumbf_io.rs
Adds streaming write support for BMFF.  Support XMP in BMFF formats.
=> Streaming write support for BMFF

sdk/src/trust_handler.rs
This is required for c2pa-node to upgrade to the latest version so that we can share the global config across threads.
=> Add `Sync` trait to `TrustHandlerConfig`

sdk/src/assertion.rs, sdk/src/asset_handlers/jpeg_io.rs, sdk/src/asset_handlers/png_io.rs, sdk/src/asset_handlers/tiff_io.rs, sdk/src/asset_io.rs, sdk/src/builder.rs, sdk/src/cose_validator.rs, sdk/src/error.rs, sdk/src/ingredient.rs, sdk/src/jumbf_io.rs, sdk/src/manifest.rs, sdk/src/openssl/rsa_signer.rs, sdk/src/openssl/rsa_validator.rs, sdk/src/resource_store.rs, sdk/src/signer.rs, sdk/src/store.rs, sdk/src/trust_handler.rs, sdk/src/utils/xmp_inmemory_utils.rs, sdk/src/validator.rs
Note: on some formats c2pa manifests fail to be removed.
On others XMP write is supposed to be implemented but read does not work.
These errors are bypassed for now but should be followed up with issues
=> (Minor) Additional unit tests and fixes for injection (or previously untested) issues.

sdk/src/assertions/bmff_hash.rs
Fixes issue uncovered in MS testing of c2patool for Merkle trees with empty proof for last leaf.
=> Allow empty Merkle proof for last leaf node.

sdk/src/manifest.rs
This was in an earlier version of #472 but seems to have been lost when it was merged.
CAWG identity assertion project needs this.
=> Let's not assume that third-party assertions are using serde_cbor

SECURITY.md
=> added final details

CONTRIBUTING.md
Changed text in CONTRIBUTING.md to link to new guidance in SECURITY.md.
=> (IGNORE) Update security guidance to link to SECURITY.md

sdk/src/store.rs
Fix bmff hash your the wrong asset in the file based manifest generation.
=> Bmff write fix

.github/workflows/ci.yml
Matches changes made recently in c2patool repo.
=> chore: Adjust when CI tests are run

README.md, sdk/src/builder.rs, sdk/src/ingredient.rs, sdk/src/manifest.rs, sdk/src/reader.rs, sdk/src/utils/hash_utils.rs
Review doc comments for Reader.
Edits to doc comments in Rust code for clarity and completeness.
TO DO:
- Change all references to errors to be to the [`Error`] enum
=> doc: Update API documentation

.github/workflows/closing-ticket.yml, .github/workflows/reopening-ticket.yml
Adding workflows to update labels as issue opens/closes to sync with JIRA
=> chore: Adding workflows to handle labels on open/close

.github/workflows/closing_ticket.yml, .github/workflows/labeling_ticket_done.yml, .github/workflows/labeling_ticket_todo.yml, .github/workflows/reopening_ticket.yml
Any non-done label will re-open ticket. Done label will close ticket.
=> chore: Updating ticket status based on labels

sdk/src/cose_validator.rs
(Codes are actually located now in `c2pa-status-tracker` crate.)
=> chore: Remove `cose_validator` dep on `validation_status`

sdk/src/asset_handlers/tiff_io.rs
Use checked_mul to prevent panic from overflow. Add test.
=> fix: Possible overflow for TIFF

.github/workflows/ci.yml, README.md, cawg_identity/Cargo.toml, docs/usage.md, export_schema/Cargo.toml, internal/crypto/Cargo.toml, internal/status-tracker/Cargo.toml, make_test_images/Cargo.toml, sdk/Cargo.toml
Required due to version updates in some dependent crates.
=> feat: Bump MSRV to 1.81.0

README.md, cli/CHANGELOG.md, cli/README.md, cli/docs/manifest.md, cli/docs/release-notes.md, cli/docs/x_509.md
Doc cleanup for move of c2patool into c2pa-rs.
=> doc: Post move cleanup

internal/crypto/src/cose/mod.rs, internal/crypto/src/cose/verify.rs, sdk/src/cose_validator.rs, sdk/src/store.rs
… which takes configuration for validation policy and performs it.
=> feat: Introduce `c2pa_crypto::cose::Verifier`

internal/crypto/src/cose/mod.rs, internal/crypto/src/cose/sign1.rs, sdk/src/cose_validator.rs
(This will allow me to make some other things private.)
=> feat: Add new function `c2pa_crypto::cose::signing_time_from_sign1`

cawg_identity/README.md
=> chore(cawg_identity): Update README

.commitlintrc.yml, internal/crypto/README.md
Tweak README content per recent code review.
=> chore(crypto): Update README

sdk/examples/data_hash.rs, sdk/src/builder.rs, sdk/src/cose_sign.rs, sdk/src/lib.rs, sdk/src/manifest.rs, sdk/src/signer.rs, sdk/src/utils/test.rs, sdk/src/utils/test_signer.rs
Also fix a bunch of warnings in the default-features case.
=> chore(sdk): Make `PreliminaryClaim` public

.github/workflows/release.yml, cli/Cargo.toml
(No-op change to c2patool's Cargo.toml to trigger new builds when we release again.)
=> fix(c2patool): Upload a distinct SBOM per platform

cawg_identity/src/builder/identity_assertion_builder.rs, sdk/src/dynamic_assertion.rs, sdk/src/store.rs
Allow DynamicAssertion to be used with synchronous Signer
=> feat: Allow synchronous DynamicAssertion

docs/release-notes.md
Small edit to release notes to fix doc build: https://github.com/contentauth/opensource.contentauth.org/actions/runs/13083344939/job/36510982062?pr=186
- [x ] This PR represents a single feature, fix, or change.
- [x ] All applicable changes have been documented.
- [x ] Any `TO DO` items (or similar) have been entered as GitHub issues and the link to that issue has been included in a comment.
=> docs: Formatting tweak to fix doc site build

sdk/src/builder.rs
The output path in this use case is a folder.  So skip the normal file checks.
=> fix: Fix broken c2patool fragment feature

docs/usage.md
=> docs: WASM building and testing

sdk/src/assertions/actions.rs
Also adds softwareAgentIndex and templateParameters fields to Action
=> feat: adds allActionsIncluded flag to Actions Assertion

cawg_identity/examples/cawg.rs
Adds WASI support for CAWG example
=> fix: Add WASI support for CAWG example

cawg_identity/src/builder/identity_assertion_builder.rs, cawg_identity/src/identity_assertion/signer_payload.rs, cawg_identity/src/tests/claim_aggregation/interop.rs, cawg_identity/src/tests/identity_assertion/built_in_signature_verifier.rs, cawg_identity/src/tests/identity_assertion/signer_payload.rs
(Q&D implementation: Will work on better testing in a day or three.)
=> feat: Add support for referenced_assertions and roles

sdk/src/reader.rs
This previously would add  a status and result in reports with missing manifests.
It is a change in behavior that will return more errors and less status, but will not cause mysteriously missing manifests.
=> fix: Return an error if a manifest cannot be read

cli/CHANGELOG.md
To fix issues that were breaking the doc site build.
=> Update c2patool CHANGELOG.md

c_api/src/c_api.rs
fix: allow c2pa_builder_sign_data_hashed_embeddable to pass a null asset pointer because that is an allowed feature
=> feat: Adds CAWG validation support to the c_api reader creation methods

Cargo.lock, cli/Cargo.toml, internal/crypto/src/lib.rs, sdk/src/crypto/mod.rs
(Second PR to fix a couple release-plz related issues in the first.)
=> feat: Merge c2pa-crypto crate into c2pa

Makefile, sdk/src/builder.rs, sdk/src/lib.rs, sdk/src/utils/test_signer.rs
Everything but test-wasi works again now.
=> chore: Repair `Makefile` after build changes

.github/workflows/library-release.yml, make_release.ps1
Builds on x86 or arm
this is a rust_native_crypto build
=> build: Windows PowerShell make_release

cli/src/info.rs
Command was misusing an API call.
=> fix: fix  c2patool --info command.

sdk/src/reader.rs
This test will only work if this feature is enabled. On another note, we should be setting up a local http server for this type of test.
=> test: feature flag `test_reader_remote_url` with feature `fetch_remote_manifests`

Cargo.lock, sdk/Cargo.toml, sdk/examples/v2show.rs, sdk/src/crypto/ocsp/fetch.rs, sdk/src/crypto/time_stamp/error.rs, sdk/src/crypto/time_stamp/http_request.rs, sdk/src/settings/mod.rs, sdk/src/settings/signer.rs, sdk/src/store.rs
Updates `ureq` to latest version.
=> chore: update ureq

c2pa_c_ffi/Cargo.toml
Enable additional features on c2pa-c-ffi:
- PDF
- Other suggested one seem to be enabled?
For https://github.com/contentauth/c2pa-rs/issues/1241.
=> fix: Enable additional features on c2pa-c-ffi

sdk/src/ingredient.rs
If `builder.thumbnail.enabled` is false then a thumbnail will not be automatically generated for ingredients. Should we introduce a separate "ingredient thumbnail" setting or use the builder?
* Closes #1330
=> fix: ingredient thumbnail generation respect settings

sdk/src/ingredient.rs, sdk/src/utils/thumbnail.rs
Fixes lints and dead code references on certain targets.
=> style: fix docs and dead code lint

.github/workflows/ci.yml
Try updating chrome to get tests to pass.
=> chore: update chrome to 140

sdk/src/assertions/metadata.rs, sdk/src/builder.rs, sdk/src/claim.rs, sdk/src/manifest.rs, sdk/tests/test_builder.rs
=> chore: backport metadata fixes

cli/tests/fixtures/trust/cawg_sign_settings.toml, sdk/examples/c2pa.toml, sdk/src/assertions/actions.rs, sdk/src/builder.rs, sdk/src/settings/builder.rs, sdk/tests/fixtures/test_settings.toml, sdk/tests/fixtures/test_settings_with_cawg_signing.toml, sdk/tests/known_good/CA_test.json, sdk/tests/test_builder.rs
Knowing I'll lose this battle ;)
=> fix: allActionsIncluded defaults to None

sdk/src/claim.rs
- Fix formatting error flagged by https://github.com/contentauth/c2pa-rs/actions/runs/18192827884/job/51791632203?pr=1468
=> chore: Fix format
